#!/bin/zsh
while read package; do
  outdatednpmdependencies "https://github.com/commonform/$package"
done <<EOS
abstract-numbering
agreement-schedules-exhibits-numbering
commonform-alex
commonform-analyze
commonform-archaic
commonform-commonmark
commonform-critique
commonform-docx
commonform-group-series
commonform-hash
commonform-html
commonform-lint
commonform-mscd
commonform-number
commonform-phrase-annotator
commonform-regexp-annotator
commonform-resolve
commonform-serialize
commonform-unmarked-uses
commonform-validate
decimal-numbering
ooxml-signature-pages
outline-numbering
plan-addenda-exhibits-numbering
resolutions-schedules-exhibits-numbering
EOS
