#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage: <Git Remote>" >/dev/stderr
  exit 1
fi

tmp=$(mktemp -d)
cleanup () {
  rm -rf "$tmp"
}
trap cleanup EXIT

git clone --quiet "$1" "$tmp"
cd "$tmp"
if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
  npm ci --quiet >/dev/null
else
  npm i --quiet >/dev/null
fi

npm audit --parseable --audit-level=moderate 2>/dev/null | sed '/^\s*$/d'
