#!/bin/sh
set -e

if ! command -v will-it-rain >/dev/null; then
  npm i -g kemitchell/will-it-rain.js
fi

if will-it-rain; then
  echo "NOAA forecasts rain today." | mutt -s "Rain Today" "kyle@kemitchell.com"
fi
