#!/bin/sh
set -e

if [ ! hash will-it-rain &>/dev/null ]; then
  npm i -g kemitchell/will-it-rain.js
fi

will-it-rain
if [ $? = 0 ]; then
  mutt -s "Rain Today" "kyle@kemitchell.com" <<< "NOAA forecasts rain today."
fi
